#!/bin/bash
# pretty sure there is a better way of doing this, but works for now...
# make it the primary display
xrandr --output HDMI1 --primary --mode 2560x1080 --right-of eDP1
# remove the other display
xrandr --output eDP1 --off
